apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: conventional-quelea-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: conventional-quelea-nodejs 
  name: conventional-quelea-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: conventional-quelea-nodejs 
