apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: conventional-quelea-nodejs 
  janus-idp.io/tekton: conventional-quelea-nodejs
  backstage.io/kubernetes-id: conventional-quelea-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: conventional-quelea-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  